// ============================================================================
// [START] FILE: firebase_options.dart
// ============================================================================
// File generated by FlutterFire CLI or created for SNEAKR Firebase Integration.
// To connect your real Firebase project:
// 1. Visit https://console.firebase.google.com and create/select your project.
// 2. Paste your project credentials below or run `flutterfire configure`.
// ============================================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions? get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }
  

  // Web Firebase Options Configuration

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywQtwyugyAu2MrhG7L2apDWZ_s8pXv_I',
    appId: '1:933251167531:web:1626b91beb900bf717816e',
    messagingSenderId: '933251167531',
    projectId: 'sneaker-shop-e44f0',
    authDomain: 'sneaker-shop-e44f0.firebaseapp.com',
    storageBucket: 'sneaker-shop-e44f0.firebasestorage.app',
    measurementId: 'G-J60R14QNCY',
  );
  // Android Firebase Options Configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd-XKe7eEK7G8jKCd-287zV_P4ib5YSxw',
    appId: '1:933251167531:android:6af0f6236fe385ed17816e',
    messagingSenderId: '933251167531',
    projectId: 'sneaker-shop-e44f0',
    storageBucket: 'sneaker-shop-e44f0.firebasestorage.app',
  );
  // iOS Firebase Options Configuration
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDemoKeyForSneakrAppIos12345678901',
    appId: '1:123456789012:ios:demo1234567890abcdef',
    messagingSenderId: '123456789012',
    projectId: 'sneakr-app-demo',
    storageBucket: 'sneakr-app-demo.appspot.com',
    iosBundleId: 'com.sneakr.app',
  );
}
// ============================================================================
// [END] FILE: firebase_options.dart
// ============================================================================
